//! System tray icon + menu, powered by the `tray-icon` crate.
//!
//! Ownership: `TrayService` owns the `TrayIcon`. Drop it to remove the icon
//! from the tray. Events flow out through `poll()` which drains the
//! global `TrayIconEvent` and `MenuEvent` receivers exposed by the crate.

use anyhow::{Context, Result};
use tray_icon::menu::{Menu, MenuEvent, MenuItem, PredefinedMenuItem};
use tray_icon::{Icon, TrayIcon, TrayIconBuilder, TrayIconEvent};

/// Menu item identifier exposed to the rest of the app.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrayMenu {
    Show,
    Palette,
    Workspace,
    Settings,
    Quit,
}

/// Tray event classification for the engine / main loop.
#[derive(Debug, Clone)]
pub enum TrayEvent {
    /// Left-click on the tray icon (outside the menu).
    IconClicked,
    /// Menu item activation.
    MenuItem(TrayMenu),
}

pub struct TrayService {
    _icon: TrayIcon,
    id_show: String,
    id_palette: String,
    id_workspace: String,
    id_settings: String,
    id_quit: String,
}

impl TrayService {
    /// Build the tray icon and menu. `icon_bytes` is typically the embedded
    /// `TRAY_ICON_PNG` from this module — see the const below.
    pub fn new(icon_bytes: &[u8]) -> Result<Self> {
        let menu = Menu::new();

        let mi_show = MenuItem::new("Show Overlay", true, None);
        let mi_palette = MenuItem::new("Command Palette", true, None);
        let mi_workspace = MenuItem::new("Open Workspace", true, None);
        let mi_settings = MenuItem::new("Settings…", true, None);
        let sep = PredefinedMenuItem::separator();
        let mi_quit = MenuItem::new("Quit Quill", true, None);

        menu.append(&mi_show).context("append Show menu item")?;
        menu.append(&mi_palette)
            .context("append Palette menu item")?;
        menu.append(&mi_workspace)
            .context("append Workspace menu item")?;
        menu.append(&mi_settings)
            .context("append Settings menu item")?;
        menu.append(&sep).context("append separator")?;
        menu.append(&mi_quit).context("append Quit menu item")?;

        let id_show = mi_show.id().0.clone();
        let id_palette = mi_palette.id().0.clone();
        let id_workspace = mi_workspace.id().0.clone();
        let id_settings = mi_settings.id().0.clone();
        let id_quit = mi_quit.id().0.clone();

        let icon = load_icon_from_png(icon_bytes).context("load tray icon")?;

        let tray = TrayIconBuilder::new()
            .with_menu(Box::new(menu))
            .with_tooltip("Quill")
            .with_icon(icon)
            .build()
            .context("build TrayIconBuilder")?;

        Ok(Self {
            _icon: tray,
            id_show,
            id_palette,
            id_workspace,
            id_settings,
            id_quit,
        })
    }

    /// Drain pending tray events and classify them.
    /// Call this from a polling timer or dedicated thread.
    pub fn poll(&self) -> Vec<TrayEvent> {
        let mut out = Vec::new();

        while let Ok(event) = TrayIconEvent::receiver().try_recv() {
            if let TrayIconEvent::Click {
                button,
                button_state,
                ..
            } = event
            {
                if matches!(button, tray_icon::MouseButton::Left)
                    && matches!(button_state, tray_icon::MouseButtonState::Up)
                {
                    out.push(TrayEvent::IconClicked);
                }
            }
        }

        while let Ok(event) = MenuEvent::receiver().try_recv() {
            let id = event.id.0.clone();
            let item = if id == self.id_show {
                TrayMenu::Show
            } else if id == self.id_palette {
                TrayMenu::Palette
            } else if id == self.id_workspace {
                TrayMenu::Workspace
            } else if id == self.id_settings {
                TrayMenu::Settings
            } else if id == self.id_quit {
                TrayMenu::Quit
            } else {
                continue;
            };
            out.push(TrayEvent::MenuItem(item));
        }

        out
    }
}

/// Embedded 32×32 PNG tray icon. Generated by build.rs from plume.svg into
/// `OUT_DIR` — kept out of the source tree so the build never dirties the
/// repo.
pub const TRAY_ICON_PNG: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/quill-tray-32.png"));

/// Decode a PNG byte slice into a `tray_icon::Icon`.
fn load_icon_from_png(bytes: &[u8]) -> Result<Icon> {
    let decoder = png::Decoder::new(bytes);
    let mut reader = decoder.read_info().context("png::Decoder::read_info")?;
    let mut buf = vec![0; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).context("png next_frame")?;
    buf.truncate(info.buffer_size());

    // tray_icon::Icon::from_rgba wants RGBA. Normalize if we got RGB.
    let rgba = match info.color_type {
        png::ColorType::Rgba => buf,
        png::ColorType::Rgb => {
            let mut out = Vec::with_capacity(buf.len() / 3 * 4);
            for chunk in buf.chunks_exact(3) {
                out.extend_from_slice(&[chunk[0], chunk[1], chunk[2], 255]);
            }
            out
        }
        other => anyhow::bail!("unsupported PNG color type: {other:?}"),
    };

    Icon::from_rgba(rgba, info.width, info.height).context("Icon::from_rgba")
}
